version: '3.7'

services:
  nginx:
    build:
      context: ./nginx
    restart: always
    depends_on:
      - db
      - gitlab
    volumes:
      - nginx_cache:/var/lib/nginx/proxy_cache
      - static:/var/www/static/:ro
      - api_cache:/var/lib/nginx/api_cache
      - local_static:/var/www/local_static/
      - acme.sh:/acme.sh:delegated
      - certs:/etc/nginx/certs
    environment:
      - ENVIRONMENT=production
      - GITLAB_SITE_HOST
      - REGISTRY_SITE_HOST
      - HTPASSWD
      - HTPASSWD_MODE
      - TLS_MODE
    ports:
      - 80:80
      - 443:443
    logging:
      driver: journald

  db:
    restart: always
    build:
      context: ./db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_HOST
    ports:
      - 127.0.0.1:5432:5432
    command:
      - "postgres"
      - "-c"
      - "max_connections=150"
      - "-c"
      - "shared_buffers=1GB" # 25% от текущей оперативной памяти
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=32MB" # shared_buffers поделить на max_connections. Если получается меньше 32МБ, то оставить 32МБ
      - "-c"
      - "maintenance_work_mem=512MB" # 10% от оперативной памяти
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    logging:
      driver: journald
      options:
        tag: db

  gitlab:
    image: gitlab/gitlab-ee:16.2.4-ee.0
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-config:/etc/gitlab
    shm_size: "256m"
    ports:
      - 8000:8000
      - 4443:443
    environment:
      VIRTUAL_HOST: ${GITLAB_HOST_NAME}
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${GITLAB_HOST_NAME}'
        letsencrypt['enable'] = false
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
            "X-Forwarded-Proto" => "https",
            "X-Forwarded-Ssl" => "on"
        }
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SHELL_SSH_PORT}
        gitlab_rails['db_adapter'] = "${POSTGRES_TYPE}"
        gitlab_rails['db_encoding'] = "unicode"
        gitlab_rails['db_host'] = "db"
        gitlab_rails['db_database'] = "${POSTGRES_NAME}"
        gitlab_rails['db_username'] = "${POSTGRES_USER}"
        gitlab_rails['db_password'] = "${POSTGRES_PASSWORD}"
        registry_external_url 'http://localhost:5000'
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['api_url'] = 'https://${REGISTRY_HOST_NAME}'
        registry['enable'] = true
        registry_nginx['enable'] = false
        registry['registry_http_addr'] = "0.0.0.0:5000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 240s
    restart: unless-stopped
    depends_on:
      - db

  registry:
    image: registry:latest
    restart: always
    ports:
      - 5000:5000
    environment:
      # - REGISTRY_AUTH=htpasswd
      # - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      # - REGISTRY_AUTH_HTPASSWD_PATH=/auth/.htpasswd
      - REGISTRY_LOG_LEVEL=debug
      - REGISTRY_STORAGE=filesystem
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=var/lib/registry
    volumes:
    - ./data:/var/lib/registry

  runner:
    image: gitlab/gitlab-runner:alpine
    restart: always
    hostname: runner-1
    depends_on:
      - gitlab
    volumes:
     - ./config/gitlab-runner:/etc/gitlab-runner
     - /var/run/docker.sock:/var/run/docker.sock

volumes:
  local_static:
  acme.sh:
  certs:
  static:
  redisdata:
  postgresdata:
  api_cache:
  nginx_cache:
  gitlab-data:
  gitlab-logs:
  gitlab-config:
